name: rift_walk_env
channels:
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - backports=1.0
  - backports.os=0.1.1
  - backports_abc=0.5
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - colorama=0.4.1
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - html5lib=1.0.1
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib_metadata=0.9
  - intel-openmp=2019.3
  - ipykernel=5.1.0
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - krb5=1.16.1
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.16
  - luigi=2.8.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2017.0.4
  - msys2-conda-epoch=20160418
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - networkx=2.3
  - notebook=5.7.8
  - numpy=1.13.3
  - openssl=1.1.1b
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - path.py=12.0.1
  - pep8=1.7.1
  - pickleshare=0.7.5
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - psycopg2=2.7.6.1
  - py4j=0.10.7
  - pygments=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pyspark=2.4.1
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pywinpty=0.5.5
  - pyzmq=18.0.0
  - qt=5.9.7
  - qtconsole=4.4.4
  - scipy=0.19.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - vc=14.1
  - vs2010_runtime=10.00.40219.1
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - widgetsnbextension=3.4.2
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - xlrd=1.2.0
  - zeromq=4.3.1
  - zipp=0.3.3
  - zlib=1.2.11
  - pip:
    - alembic==0.9.10
    - apache-airflow==1.10.3
    - babel==2.7.0
    - chardet==3.0.4
    - click==7.0
    - configparser==3.5.3
    - croniter==0.3.30
    - dill==0.2.9
    - docopt==0.6.2
    - docutils==0.14
    - findspark==1.3.0
    - flask==1.0.3
    - flask-admin==1.5.3
    - flask-appbuilder==1.12.3
    - flask-babel==0.12.2
    - flask-caching==1.3.3
    - flask-login==0.4.1
    - flask-openid==1.2.5
    - flask-sqlalchemy==2.4.0
    - flask-swagger==0.2.13
    - flask-wtf==0.14.2
    - funcsigs==1.0.0
    - future==0.16.0
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - gunicorn==19.9.0
    - idna==2.8
    - iso8601==0.1.12
    - itsdangerous==1.1.0
    - jinja2==2.10
    - json-merge-patch==0.2
    - lockfile==0.12.2
    - lxml==4.3.3
    - mako==1.0.10
    - markdown==2.6.11
    - ordereddict==1.1
    - pendulum==1.4.4
    - pip==19.1.1
    - psutil==5.6.2
    - python-daemon==2.1.2
    - python-dotenv==0.10.2
    - python-editor==1.0.4
    - python3-openid==3.1.0
    - pytzdata==2019.1
    - pyyaml==5.1
    - requests==2.22.0
    - setproctitle==1.1.10
    - smmap2==2.0.5
    - sqlalchemy==1.2.19
    - tabulate==0.8.3
    - tenacity==4.12.0
    - text-unidecode==1.2
    - thrift==0.11.0
    - typing==3.6.6
    - tzlocal==1.5.1
    - unicodecsv==0.14.1
    - urllib3==1.25.3
    - werkzeug==0.14.1
    - wtforms==2.2.1
    - zope-deprecation==4.4.0

